# Generated by Django 6.0.6 on 2026-06-08 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('activite', models.CharField(max_length=100)),
                ('anciennete_annees', models.IntegerField()),
                ('nb_categories', models.IntegerField()),
                ('freq_stock_par_an', models.IntegerField(help_text='Nombre de réapprovisionnements par an')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='KISScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.FloatField()),
                ('flux_score', models.FloatField()),
                ('resilience', models.FloatField()),
                ('kis', models.FloatField()),
                ('profil', models.CharField(max_length=50)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='FluxMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('montant_entrant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'ordering': ['mois'],
                'unique_together': {('client', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'ordering': ['mois'],
                'unique_together': {('client', 'mois')},
            },
        ),
    ]
